packages:
  - "apps/*"
  - "tools/*"
  - "packages/core"
  - "packages/config/*"
  - "packages/ui/*"
  - "packages/features/*"
  - "packages/modules/*"
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
  - onnxruntime-node
